### Blindar jugador
POST http://localhost:3000/api/clausulas/102/jugadores/200/blindar
Content-Type: application/json

{
  "monto_incremento": 1000000
}

### Ejecutar cláusula
POST http://localhost:3000/api/clausulas/96/jugadores/200/ejecutar-clausula