### Crear un nuevo equipo (requiere autenticación previa)
# Primero, asegúrate de haber ejecutado una petición de LOGIN exitosa
# desde tu archivo auth.http para obtener la cookie de sesión.
POST http://localhost:3000/api/equipos
Content-Type: application/json

{
  "nombre": "Club Atletico AntiPinguinos"
}

### Obtener el equipo del usuario autenticado (requiere autenticación previa)
GET http://localhost:3000/api/equipos/detalle-equipo/11
Content-Type: application/json

### Realizar un intercambio de jugadores en el equipo (requiere autenticación previa)
PATCH http://localhost:3000/api/equipos/mi-equipo/intercambio
Content-Type: application/json

{
  "jugadorSaleId": 1,
  "jugadorEntraId": 60
}
// EL 196 el veliz, gracias dios por tanto futbol
### Cambiar un titular por un suplente (requiere autenticación previa)
PATCH http://localhost:3000/api/equipos/mi-equipo/11/alineacion
Content-Type: application/json

{
  "jugadorTitularId": 368,
  "jugadorSuplenteId": 283
}

### Obtener las jornadas de un equipo donde puntuó (requiere autenticación previa)
GET http://localhost:3000/api/equipos/73/historial

### Obtener Las puntuaciones de un equipo para una jornada.
GET http://localhost:3000/api/equipos/8/puntos/jornadas/2
Content-Type: application/json

### Obtener Las puntuaciones de un equipo para una jornada.

GET http://localhost:3000/api/equipos/todos
Content-Type: application/json

### Vender un jugador del equipo (requiere autenticación previa)
POST http://localhost:3000/api/equipos/mi-equipo/4/vender-jugador
Content-Type: application/json

{
  "jugadorId": 283
}

### Cambiar estado de un jugador
PATCH http://localhost:3000/api/equipos/mi-equipo/4/cambiar-estado
Content-Type: application/json

{
  "jugadorId": 283
}
