### Hacer una oferta por un jugador
POST http://localhost:3000/api/mercado-puja/equipo/95/ofertar
Content-Type: application/json

{
  "itemMercadoId": 33,
  "monto": 4000000
}

### Actualizar oferta (mismo endpoint)
POST http://localhost:3000/api/mercado-puja/equipo/4/ofertar
Content-Type: application/json

{
  "itemMercadoId": 1,
  "monto": 15000000
}

### Cancelar oferta
DELETE http://localhost:3000/api/mercado-puja/puja/4/cancelar

### Ver mis ofertas activas
GET http://localhost:3000/api/mercado-puja/equipo/95/mis-ofertas