### Abrir mercado para un torneo (Admin)
POST http://localhost:3000/api/mercado/abrir
Content-Type: application/json

{
  "torneoId": 38
}

### Cerrar mercado (Admin)
POST http://localhost:3000/api/mercado/4/cerrar
Content-Type: application/json

### Obtener mercado activo de un torneo (Usuario autenticado)
GET http://localhost:3000/api/mercado/activo/torneo/36  
Content-Type: application/json