### Hacer una oferta por un jugador
POST http://localhost:3000/api/mercado-puja/equipo/6/ofertar
Content-Type: application/json

{
  "itemMercadoId": 1,
  "monto": 6300000
}

### Actualizar oferta (mismo endpoint)
POST http://localhost:3000/api/mercado-puja/equipo/4/ofertar
Content-Type: application/json

{
  "itemMercadoId": 1,
  "monto": 15000000
}

### Cancelar oferta
DELETE http://localhost:3000/api/mercado-puja/puja/3/cancelar

### Ver mis ofertas activas
GET http://localhost:3000/api/mercado-puja/equipo/6/mis-ofertas