### GET all clubs
http://localhost:3000/api/clubs


### POST a club
# @nombre createClub
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "nombre": "River",
  "id_api": "12345"
}

### GET one club
http://localhost:3000/api/clubs/1

### PUT a club
PUT http://localhost:3000/api/clubs/2
Content-Type: application/json

{
  "nombre": "River",
  "id_api": "12345"
}

### POST a club
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "nombre": "Rosario Central",
  "id_api": "12345"
}

### POST a club
# @nombre createclubToDelete
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "nombre": "Newell's Old Boys",
  "id_api": "12346"
}

### PATCH a club
PATCH http://localhost:3000/api/clubs/5
Content-Type: application/json

{
  "nombre": "Pinguinitos Fc"
}

### DELETE a club
DELETE http://localhost:3000/api/clubs/