### GET all clubs
http://localhost:3000/api/clubs


### POST a club
# @name createClub
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "name": "Boca Juniors"
}

### ID
@id = {{createClub.response.body.data.id}}

### GET one club
http://localhost:3000/api/clubs/1

### PUT a club
PUT http://localhost:3000/api/clubs/1
Content-Type: application/json

{
  "name": "River Plate"
}

### POST a club
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "name": "Rosario Central"
}

### POST a club
# @name createclubToDelete
POST http://localhost:3000/api/clubs
Content-Type: application/json

{
  "name": "Newell's Old Boys"
}
### DELETE a club
@idToDelete = {{createclubToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/clubs/{{idToDelete}}

### PATCH a club
PATCH http://localhost:3000/api/clubs/8
Content-Type: application/json

{
  "name": "Pinguinitos Fc"
}

### DELETE a club
DELETE http://localhost:3000/api/clubs/5