  ### POST /api/auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tomasribotta20@gmail.com",
  "password": "TeAmoMazalan69"
}

### POST /api/auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "pedrohola3@gmail.com",
  "password": "UsuarioPrueba1"
}
### POST /api/auth/register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "UsuarioPrueba1",
  "email": "Prueba@gmail.com",
  "password": "UsuarioPrueba1"
}

### POST /api/auth/logout
POST http://localhost:3000/api/auth/logout

### POST /api/auth/refreshToken
POST http://localhost:3000/api/auth/refreshToken

### PUT /api/auth/new-password
PUT http://localhost:3000/api/auth/new-password
Content-Type: application/json

{
  "newPassword": "Admin123"
}

### PUT /api/auth/forgot-password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "arielmazalan1@gmail.com"
}

#########################################################
### Login Admin
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}
###

POST http://localhost:3000/api/auth/new-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImFyaWVsbWF6YWxhbjFAZ21haWwuY29tIiwidHlwZSI6InBhc3N3b3JkX3Jlc2V0IiwiaWF0IjoxNzU3MTcwNzQwLCJleHAiOjE3NTcxNzEzNDB9.c0lwjPZs8THjn7Y2-ot7XayvvnE18mXDOhrMVu3E1t0
Content-Type: application/json

{
  "password": "ariel123"
}

#################################################################


### Login Admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}

### Login Test User 1
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser1@test.com",
  "password": "TestPass123"
}

### Login Test User 2
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser2@test.com",
  "password": "TestPass123"
}

### Login Test User 3
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser3@test.com",
  "password": "TestPass123"
}

### Login Test User 4
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser4@test.com",
  "password": "TestPass123"
}

### Login Test User 5
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser5@test.com",
  "password": "TestPass123"
}

### Login Test User 6
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser6@test.com",
  "password": "TestPass123"
}

### Login Test User 7
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser7@test.com",
  "password": "TestPass123"
}

### Login Test User 8
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser8@test.com",
  "password": "TestPass123"
}

### Login Test User 9
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser9@test.com",
  "password": "TestPass123"
}

### Login Test User 10
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser10@test.com",
  "password": "TestPass123"
}

### Login Test User 11
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser11@test.com",
  "password": "TestPass123"
}

### Login Test User 12
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser12@test.com",
  "password": "TestPass123"
}

### Login Test User 13
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser13@test.com",
  "password": "TestPass123"
}

### Login Test User 14
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser14@test.com",
  "password": "TestPass123"
}

### Login Test User 15
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser15@test.com",
  "password": "TestPass123"
}