### POST /api/auth/login    //Puede pasar que el usuario siga con la cookie a pesar de haberlo borrado de la base de datos
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "TomasRibotta20@gmail.com",
  "password": "TeAmoMazalan69"
}

### POST /api/auth/register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Admin",
  "email": "admin@admin.com",
  "password": "admin123"
}

### POST /api/auth/logout
POST http://localhost:3000/api/auth/logout

### POST /api/auth/refreshToken
POST http://localhost:3000/api/auth/refreshToken

### PUT /api/auth/new-password
PUT http://localhost:3000/api/auth/new-password
Content-Type: application/json

{
  "newPassword": "Admin123"
}

### PUT /api/auth/forgot-password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "arielmazalan1@gmail.com"
}

#########################################################
### Login Admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}
###

POST http://localhost:3000/api/auth/new-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImFyaWVsbWF6YWxhbjFAZ21haWwuY29tIiwidHlwZSI6InBhc3N3b3JkX3Jlc2V0IiwiaWF0IjoxNzU3MTcwNzQwLCJleHAiOjE3NTcxNzEzNDB9.c0lwjPZs8THjn7Y2-ot7XayvvnE18mXDOhrMVu3E1t0
Content-Type: application/json

{
  "password": "ariel123"
}
